// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectAW.Infrastructure.Data;

#nullable disable

namespace ProjectAW.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261009194050_sequence_Guias")]
    partial class sequence_Guias
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("SeqGuiaEntrada");

            modelBuilder.HasSequence<int>("SeqGuiaSalida");

            modelBuilder.HasSequence<int>("SeqGuiaTraslado");

            modelBuilder.Entity("ProjectAW.Modules.Guias.Entities.CabeceraGuia", b =>
                {
                    b.Property<int>("IdGuia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGuia"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaProgramada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("IdAlmacenDestino")
                        .HasColumnType("int");

                    b.Property<int?>("IdAlmacenOrigen")
                        .HasColumnType("int");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("NumeroDocumentoReferencia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroGuia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TipoDocumentoReferencia")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TipoOperacion")
                        .HasColumnType("int");

                    b.HasKey("IdGuia");

                    b.HasIndex("IdAlmacenDestino");

                    b.HasIndex("IdAlmacenOrigen");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("NumeroGuia")
                        .IsUnique();

                    b.ToTable("CabeceraGuias", null, t =>
                        {
                            t.HasCheckConstraint("CK_CabeceraGuia_Operacion", "(TipoOperacion = 1 AND IdProveedor IS NOT NULL AND IdAlmacenDestino IS NOT NULL\r\n                       AND IdCliente IS NULL AND IdAlmacenOrigen IS NULL)\r\n                  OR (TipoOperacion = 2 AND IdAlmacenOrigen IS NOT NULL AND IdCliente IS NOT NULL\r\n                       AND IdProveedor IS NULL AND IdAlmacenDestino IS NULL)\r\n                  OR (TipoOperacion = 3 AND IdAlmacenOrigen IS NOT NULL AND IdAlmacenDestino IS NOT NULL\r\n                       AND IdAlmacenOrigen <> IdAlmacenDestino\r\n                       AND IdProveedor IS NULL AND IdCliente IS NULL)");
                        });
                });

            modelBuilder.Entity("ProjectAW.Modules.Guias.Entities.DetalleGuia", b =>
                {
                    b.Property<int>("IdGuiaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdGuiaDetalle"));

                    b.Property<decimal>("CantidadEsperada")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("IdGuia")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.HasKey("IdGuiaDetalle");

                    b.HasIndex("IdGuia");

                    b.HasIndex("IdProducto");

                    b.ToTable("DetalleGuias", null, t =>
                        {
                            t.HasCheckConstraint("CK_DetalleGuia_Cantidad", "CantidadEsperada > 0");
                        });
                });

            modelBuilder.Entity("ProjectAW.Modules.Maestros.Almacenes.Entities.Almacen", b =>
                {
                    b.Property<int>("IdAlmacen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAlmacen"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("FchModificacion")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FchRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("IdAlmacen");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Almacenes");
                });

            modelBuilder.Entity("ProjectAW.Modules.Maestros.Categorias.Entities.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ProjectAW.Modules.Maestros.Clientes.Entities.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Correo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FchModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FchRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdTipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdTipoDocumento");

                    b.HasIndex("NumeroDocumento")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("ProjectAW.Modules.Maestros.Productos.Entities.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("FchModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FchRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Lote")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdProducto");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("IdCategoria");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ProjectAW.Modules.Maestros.Proveedores.Entities.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("CorreoContacto")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FchModificacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FchRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdTipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("NombreContacto")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TelefonoContacto")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdProveedor");

                    b.HasIndex("IdTipoDocumento");

                    b.HasIndex("NumeroDocumento")
                        .IsUnique();

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("ProjectAW.Modules.Maestros.Roles.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdRol");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ProjectAW.Modules.Maestros.TipoDocumentos.Entities.TipoDocumento", b =>
                {
                    b.Property<int>("IdTipoDocumento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoDocumento"));

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdTipoDocumento");

                    b.HasIndex("Documento")
                        .IsUnique();

                    b.ToTable("TipoDocumento");
                });

            modelBuilder.Entity("ProjectAW.Modules.Maestros.Ubicaciones.Entities.Ubicacion", b =>
                {
                    b.Property<int>("IdUbicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUbicacion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("FchModificacion")
                        .ValueGeneratedOnUpdate()
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FchRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdAlmacen")
                        .HasColumnType("int");

                    b.HasKey("IdUbicacion");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("IdAlmacen");

                    b.ToTable("Ubicaciones");
                });

            modelBuilder.Entity("ProjectAW.Modules.Seguridad.Usuarios.Entitites.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("FechaActualizada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProjectAW.Modules.Guias.Entities.CabeceraGuia", b =>
                {
                    b.HasOne("ProjectAW.Modules.Maestros.Almacenes.Entities.Almacen", null)
                        .WithMany()
                        .HasForeignKey("IdAlmacenDestino")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectAW.Modules.Maestros.Almacenes.Entities.Almacen", null)
                        .WithMany()
                        .HasForeignKey("IdAlmacenOrigen")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectAW.Modules.Maestros.Clientes.Entities.Cliente", null)
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProjectAW.Modules.Maestros.Proveedores.Entities.Proveedor", null)
                        .WithMany()
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ProjectAW.Modules.Guias.Entities.DetalleGuia", b =>
                {
                    b.HasOne("ProjectAW.Modules.Guias.Entities.CabeceraGuia", null)
                        .WithMany("Detalles")
                        .HasForeignKey("IdGuia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectAW.Modules.Maestros.Productos.Entities.Producto", null)
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("ProjectAW.Modules.Maestros.Clientes.Entities.Cliente", b =>
                {
                    b.HasOne("ProjectAW.Modules.Maestros.TipoDocumentos.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany("Clientes")
                        .HasForeignKey("IdTipoDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("ProjectAW.Modules.Maestros.Productos.Entities.Producto", b =>
                {
                    b.HasOne("ProjectAW.Modules.Maestros.Categorias.Entities.Categoria", "Categoria")
                        .WithMany("Producto")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("ProjectAW.Modules.Maestros.Proveedores.Entities.Proveedor", b =>
                {
                    b.HasOne("ProjectAW.Modules.Maestros.TipoDocumentos.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany("Proveedores")
                        .HasForeignKey("IdTipoDocumento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("ProjectAW.Modules.Maestros.Ubicaciones.Entities.Ubicacion", b =>
                {
                    b.HasOne("ProjectAW.Modules.Maestros.Almacenes.Entities.Almacen", "Almacen")
                        .WithMany("Ubicaciones")
                        .HasForeignKey("IdAlmacen")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Almacen");
                });

            modelBuilder.Entity("ProjectAW.Modules.Seguridad.Usuarios.Entitites.Usuario", b =>
                {
                    b.HasOne("ProjectAW.Modules.Maestros.Roles.Entities.Rol", "rol")
                        .WithMany("Usuario")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("rol");
                });

            modelBuilder.Entity("ProjectAW.Modules.Guias.Entities.CabeceraGuia", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("ProjectAW.Modules.Maestros.Almacenes.Entities.Almacen", b =>
                {
                    b.Navigation("Ubicaciones");
                });

            modelBuilder.Entity("ProjectAW.Modules.Maestros.Categorias.Entities.Categoria", b =>
                {
                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ProjectAW.Modules.Maestros.Roles.Entities.Rol", b =>
                {
                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProjectAW.Modules.Maestros.TipoDocumentos.Entities.TipoDocumento", b =>
                {
                    b.Navigation("Clientes");

                    b.Navigation("Proveedores");
                });
#pragma warning restore 612, 618
        }
    }
}
